library(dplyr)
library(plyr)
library(ggplot2)

#Read in all of the csv files of the datasets for Permanent Residents from the website
year15 <- read.csv("PERM_Disclosure_Data_FY15_Q4.csv", header = TRUE)
year16 <- read.csv("PERM_Disclosure_Data_FY16.csv", header = TRUE)
year17 <- read.csv("PERM_Disclosure_Data_FY17.csv", header = TRUE)
year18 <- read.csv("PERM_Disclosure_Data_FY2018_EOY.csv", header = TRUE)
year19 <- read.csv("PERM_Disclosure_Data_FY2019.csv", header = TRUE)
year14 <- read.csv("PERM_FY14_Q4.csv", header = TRUE)
year8 <- read.csv("PERM_FY2008.csv", header = TRUE)
year9 <- read.csv("PERM_FY2009.csv", header = TRUE)
year10 <- read.csv("PERM_FY2010.csv", header = TRUE)
year11 <- read.csv("PERM_FY2011.csv", header = TRUE)
year12 <- read.csv("PERM_FY2012_Q4.csv", header = TRUE)
year13 <- read.csv("PERM_FY2013.csv", header = TRUE)

#Convert the datasets to data frames
y17 <- as_data_frame(year17)
y16 <- as_data_frame(year16)
y15 <- as_data_frame(year15)
y14 <- as_data_frame(year14)
y13 <- as_data_frame(year13)
y12 <- as_data_frame(year12)
y11 <- as_data_frame(year11)
y10 <- as_data_frame(year10)
y9 <- as_data_frame(year9)
y8 <- as_data_frame(year8)

#Combine all of the dataframes
uno <- rbind.fill(y17, y16)
dos <- rbind.fill(uno, y15)
tres <- rbind.fill(dos, y14)
quatro <- rbind.fill(tres, y13)
cinco <- rbind.fill(quatro, y12)
seis <- rbind.fill(cinco, y11)
siete <- rbind.fill(seis, y10)
ocho <- rbind.fill(siete, y9)
combineddata <- rbind.fill(ocho, y8)

#Write the data frame into a csv file
write.csv(combineddata, file = "combinedpermanent.csv")
c <- read.csv("combinedpermanent.csv", header = TRUE)
co <- as_data_frame(c)

#Read in all of the csv files of the datasets for H2A applications from the website
year15 <- read.csv("H-2A_Disclosure_Data_FY15_Q4.csv", header = TRUE)
year16 <- read.csv("H-2A_Disclosure_Data_FY16.csv", header = TRUE)
year17 <- read.csv("H-2A_Disclosure_Data_FY17.csv", header = TRUE)
year18 <- read.csv("H-2A_Disclosure_Data_FY2018_EOY.csv", header = TRUE)
year19 <- read.csv("H-2A_Disclosure_Data_FY2019.csv", header = TRUE)
year14 <- read.csv("H-2A_FY14_Q4.csv", header = TRUE)
year8 <- read.csv("H2A_FY2008.csv", header = TRUE)
year9 <- read.csv("H2A_FY2009.csv", header = TRUE)
year10 <- read.csv("H-2A_FY2010.csv", header = TRUE)
year11 <- read.csv("H-2A_FY2011.csv", header = TRUE)
year12 <- read.csv("H-2A_FY2012.csv", header = TRUE)
year13 <- read.csv("H2A_FY2013.csv", header = TRUE)

#Convert the datasets to data frames
y17 <- as_data_frame(year17)
y16 <- as_data_frame(year16)
y15 <- as_data_frame(year15)
y14 <- as_data_frame(year14)
y13 <- as_data_frame(year13)
y12 <- as_data_frame(year12)
y11 <- as_data_frame(year11)
y10 <- as_data_frame(year10)
y9 <- as_data_frame(year9)
y8 <- as_data_frame(year8)

#Combine all of the dataframes
uno <- rbind.fill(y17, y16)
dos <- rbind.fill(uno, y15)
tres <- rbind.fill(dos, y14)
quatro <- rbind.fill(tres, y13)
cinco <- rbind.fill(quatro, y12)
seis <- rbind.fill(cinco, y11)
siete <- rbind.fill(seis, y10)
ocho <- rbind.fill(siete, y9)
combi <- rbind.fill(ocho, y8)

write.csv(combi, file = "combinedH2A.csv")
c <- read.csv("combinedH2A.csv", header = TRUE)
co <- as_data_frame(c)

#Read in all of the csv files of the datasets for H-2B from the website
year15 <- read.csv("H-2B_Disclosure_Data_FY15_Q4.csv", header = TRUE)
year16 <- read.csv("H-2B_Disclosure_Data_FY16.csv", header = TRUE)
year17 <- read.csv("H-2B_Disclosure_Data_FY17.csv", header = TRUE)
year18 <- read.csv("H-2B_Disclosure_Data_FY2018_EOY.csv", header = TRUE)
year19 <- read.csv("H-2B_Disclosure_Data_FY2019.csv", header = TRUE)
year14 <- read.csv("H-2B_FY14_Q4.csv", header = TRUE)
year8 <- read.csv("H-2B_FY2008.csv", header = TRUE)
year9 <- read.csv("H-2B_FY2009.csv", header = TRUE)
year10 <- read.csv("H-2B_FY2010.csv", header = TRUE)
year11 <- read.csv("H-2B_FY2011.csv", header = TRUE)
year12 <- read.csv("H-2B_FY2012_Q4.csv", header = TRUE)
year13 <- read.csv("H-2B_FY2013.csv", header = TRUE)

#Convert the datasets to data frames
y17 <- as_data_frame(year17)
y16 <- as_data_frame(year16)
y15 <- as_data_frame(year15)
y14 <- as_data_frame(year14)
y13 <- as_data_frame(year13)
y12 <- as_data_frame(year12)
y11 <- as_data_frame(year11)
y10 <- as_data_frame(year10)
y9 <- as_data_frame(year9)
y8 <- as_data_frame(year8)

#Combine all of the dataframes
uno <- rbind.fill(y17, y16)
dos <- rbind.fill(uno, y15)
tres <- rbind.fill(dos, y14)
quatro <- rbind.fill(tres, y13)
cinco <- rbind.fill(quatro, y12)
seis <- rbind.fill(cinco, y11)
siete <- rbind.fill(seis, y10)
ocho <- rbind.fill(siete, y9)
combi <- rbind.fill(ocho, y8)

write.csv(combi, file = "combinedH2A.csv")
c <- read.csv("combinedH2B.csv", header = TRUE)
co <- as_data_frame(c)
