---
title: "eda"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data and packages

```{r load-data-package, message=FALSE}
library(tidyverse)
library(modelr)
library(caret)
library(broom)
library(maps)
library(e1071)

# Load permanent worker data
perm <- read_csv("data/perm_clean.csv")

# Map data
state_data <- map_data("state")
state_data <- fortify(state_data)
world_data <- map_data("world")
world_data <- world_data %>% filter(region != "Antarctica")
world_data <- fortify(world_data)
```

## Data wrangling

```{r data-wrangle}
# Wrangle original variables 
perm <- perm %>%
  # Collapse CASE_STATUS
  mutate(CASE_STATUS = case_when(
    CASE_STATUS == "DENIED" ~ "Denied",
    CASE_STATUS == "CERTIFIED" ~ "Certified",
    CASE_STATUS == "CERTIFIED-EXPIRED" ~ "Certified-Expired",
    CASE_STATUS == "WITHDRAWN" ~ "Withdrawn",
    TRUE ~ CASE_STATUS
  )) %>%
  # Factor education w/ ref = "None"
  mutate(JOB_INFO_EDUCATION = relevel(factor(JOB_INFO_EDUCATION), ref = "None"))

# Separate date into month, day, year
perm <- perm %>%
  separate(DECISION_DATE, c("MONTH", "DAY", "YEAR"),
           sep = "/", remove = FALSE)
perm <- perm %>%
  mutate(MONTH = as.numeric(MONTH), DAY = as.numeric(DAY),
         YEAR = as.numeric(paste0("20", YEAR))) %>%
  mutate(DECISION_DATE = as.Date(DECISION_DATE, "%m/%d/%y"))

# Add binary var for certified/not certified
perm <- perm %>%
  filter(!is.na(CASE_STATUS)) %>%
  mutate(CERT = case_when(
    CASE_STATUS %in% c("Certified", "Certified-Expired") ~ "Certified",
    CASE_STATUS == "Denied" ~ "Not Certified",
    TRUE ~ NA_character_),
    CERT_BIN = case_when(
      CASE_STATUS %in% c("Certified", "Certified-Expired") ~ 1,
      CASE_STATUS == "Denied" ~ 0,
      TRUE ~ NA_real_))

perm <- perm %>%
  mutate(CERT_BIN = factor(CERT_BIN, levels = c(0, 1)))

# Add presidential administrations
perm <- perm %>%
  mutate(pres = case_when(
    DECISION_DATE <= as.Date("2009-08-01") ~ "Bush",
    DECISION_DATE < as.Date("2017-10-08") ~ "Obama",
    DECISION_DATE >= as.Date("2017-10-08") ~ "Trump",
    TRUE ~ NA_character_)) %>%
  mutate(pres = relevel(factor(pres), ref = "Bush"))

# Add Party
perm <- perm %>%
  mutate(pres_party = case_when(
    DECISION_DATE <= as.Date("2009-08-01") ~ "Republican",
    DECISION_DATE < as.Date("2017-10-08") ~ "Democrat",
    DECISION_DATE >= as.Date("2017-10-08") ~ "Republican",
    TRUE ~ NA_character_
  )) %>%
  mutate(pres_party = relevel(factor(pres_party), ref = "Republican"))
```

## Data visualization

### Certification over time

```{r cert-time}
perm %>%
  filter(CERT == "Certified") %>%
  count(YEAR) %>%
  ggplot(aes(x = YEAR, y = n, color = "red")) +
  geom_point() +
  geom_line() +
  guides(color = FALSE) +
  labs(title = "Permanent Worker Certifications over Time",
       subtitle = "From 2008 to 2018",
       x = "Year",
       y = "Number Certified") +
  scale_y_continuous(limits = c(0, 1.5E5))

perm %>%
  filter(!is.na(CERT)) %>%
  group_by(YEAR) %>%
  count(CERT) %>%
  mutate(prop = n / sum(n)) %>%
  filter(CERT == "Certified") %>%
  ggplot(aes(x = YEAR, y = prop, color = CERT)) +
  geom_point() +
  geom_line() +
  guides(color = FALSE) +
  labs(title = "Certification Rates over Time",
       subtitle = "From 2008 - 2018",
       x = "Year",
       y = "Proportion Certified") +
  scale_y_continuous(limits = c(0, 1))
```

```{r cert-political}
perm %>%
  filter(!is.na(CERT)) %>%
  group_by(pres) %>%
  count(CERT) %>%
  mutate(prop = n / sum(n)) %>%
  ggplot(aes(x = pres, y = prop, fill = CERT)) +
  geom_bar(stat = "identity") +
  labs(title = "Certification Rates by Administration",
       subtitle = "From 2008 to 2019",
       x = "Presidential Administration",
       y = "Proportion",
       fill = "Status")
```

### Certification by country

```{r country-data-viz}
perm_country <- perm %>%
  # Filter N/A Certs
  filter(!is.na(CERT)) %>%
  group_by(COUNTRY_OF_CITIZENSHIP) %>%
  count(CERT) %>%
  mutate(prop = n / sum(n)) %>%
  # Don't count incomplete data 
  filter(!is.na(COUNTRY_OF_CITIZENSHIP))

# Compute overall average of accepted applicants
prop_accepted <- perm %>%
  count(CERT) %>%
  mutate(prop_accepted = n / sum(n)) %>%
  filter(CERT == "Certified") %>%
  pull(prop_accepted)

# Top 10 proportion of countries w/ > 500 applicants
perm_country %>%
  filter(sum(n) > 500) %>%
  filter(CERT == "Certified") %>%
  arrange(desc(prop)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(COUNTRY_OF_CITIZENSHIP, prop), 
             y = prop)) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = prop_accepted,
                 colour = "Average Prop"),
             linetype = "dashed", show.legend = TRUE) +
  guides(colour = guide_legend(title = NULL)) +
  coord_flip() +
  labs(title = "Countries with Top 10 Acceptance Rate for Permanent Workers, 2008 - 2019",
       subtitle = "For countries n > 500",
       x = "Country",
       y = "Proportion of Certified Applicants")

# Bottom 10 proportion of countries w/ > 500 applicants
perm_country %>%
  filter(sum(n) > 500) %>%
  filter(CERT == "Certified") %>%
  arrange(prop) %>%
  head(10) %>%
  ggplot(aes(x = reorder(COUNTRY_OF_CITIZENSHIP, -prop), 
             y = prop)) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = prop_accepted,
                 colour = "Average Prop"),
             linetype = "dashed", show.legend = TRUE) +
  guides(colour = guide_legend(title = NULL)) +
  coord_flip() +
  labs(title = "Countries with Bottom 10 Acceptance Rate for Permanent Workers, 2008 - 2019",
       subtitle = "For countries n > 500",
       x = "Country",
       y = "Proportion of Certified Applicants")

perm_country %>%
  filter(CERT == "Certified") %>%
  ggplot(aes(x = prop)) +
  geom_histogram() +
  geom_vline(aes(fill = "Average Prop."),
             xintercept = prop_accepted,
             colour = "red",
             linetype = "dashed") +
  labs(title = "Distribution of Permanent Worker Acceptance Rates",
       subtitle = "All countries, 2008 - 2019",
       x = "Proportion Accepted",
       y = "Number of Countries")

# TODO: Geospatial visualization by country and prop of certification
```

### Education

```{r cert-education}
# Certification by Education
perm %>%
  filter(!is.na(CERT), !is.na(JOB_INFO_EDUCATION)) %>%
  group_by(JOB_INFO_EDUCATION) %>%
  count(CERT) %>%
  mutate(prop = n / sum(n)) %>%
  ungroup() %>%
  filter(CERT == "Certified") %>%
  ggplot(aes(x = reorder(JOB_INFO_EDUCATION, -prop), y = prop, fill = "red")) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = prop_accepted, colour = "Overall Rate"), 
             linetype = "dashed", show.legend = TRUE) +
  scale_color_manual(values = c("black", "grey")) +
  guides(fill = FALSE, colour = guide_legend(title = NULL)) +
  coord_flip() +
  labs(title = "Certification Rate by Education Levels",
       subtitle = "From 2008 to 2018",
       x = "Education Level",
       y = "Proportion Accepted")

perm_major <- perm %>%
  filter(!is.na(JOB_INFO_MAJOR)) %>%
  group_by(JOB_INFO_MAJOR) %>%
  count(CERT) %>% 
  mutate(prop = n / sum(n)) %>% 
  ungroup() %>% 
  filter(CERT =="Certified", n > 30) %>%
  arrange(desc(prop))

# Majors w/ highest acceptance
perm_major %>%
  head(10) %>% 
  select(JOB_INFO_MAJOR, prop)

# Majors w/ lowest acceptance
perm_major %>%
  tail(10) %>%
  select(JOB_INFO_MAJOR, prop)

# Add binary indicator for compsci
perm <- perm %>%
  mutate(COMPSCI = case_when(
    !is.na(JOB_INFO_MAJOR) &
    str_detect(JOB_INFO_MAJOR,
               regex("com.*sci", ignore_case = TRUE)) ~ "Yes",
    !is.na(JOB_INFO_MAJOR) ~ "No",
    TRUE ~ NA_character_
  )) %>%
  mutate(COMPSCI = relevel(factor(COMPSCI), ref = "No"))
```

### Certification by region

```{r region-data-viz}
# TODO: Recode countries by region and find certification proportion by regions

# Employer state
perm <- perm %>%
  mutate(EMPLOYER_STATE_FULL = tolower(state.name[match(EMPLOYER_STATE, state.abb)]))

perm_states <- perm %>%
  group_by(EMPLOYER_STATE_FULL) %>%
  count(CERT) %>%
  mutate(prop = n / sum(n)) %>%
  ungroup() %>%
  filter(CERT == "Certified")

# Certification counts
ggplot() +
# Outline of US states
  geom_map(data = state_data, map = state_data,
           aes(x = long, y = lat, map_id = region),
           fill = "#F5F5F5", colour = "grey50") +
  # Heatmap of acceptance proportion
  geom_map(data = perm_states, map = state_data,
           aes(fill = n, map_id = EMPLOYER_STATE_FULL)) +
  scale_fill_gradient(low = "#F5F5F5", high = "#000080") +
  labs(title = "State Distribution of Certifications",
       subtitle = "From 2008 to 2018",
       x = "Longitude",
       y = "Latitude",
       fill = "Number Certified")

# Certification rate
ggplot() +
# Outline of US states
  geom_map(data = state_data, map = state_data,
           aes(x = long, y = lat, map_id = region),
           fill = "#F5F5F5", colour = "grey50") +
  # Heatmap of acceptance proportion
  geom_map(data = perm_states, map = state_data,
           aes(fill = prop, map_id = EMPLOYER_STATE_FULL)) +
  scale_fill_gradient(low = "#F5F5F5", high = "#000080") +
  labs(title = "State Distribution of Certification Rates",
       subtitle = "From 2008 to 2018",
       x = "Longitude",
       y = "Latitude",
       fill = "Certif. Rate")
```

### Logistic Regression Model

```{r logit-model}
perm$JOB_INFO_EDUCATION <- relevel(factor(perm$JOB_INFO_EDUCATION), ref = "None")
full_log_cert <- glm(CERT_BIN ~ YEAR + 
                       JOB_INFO_EDUCATION +
                       PW_AMOUNT_9089 +
                       EMPLOYER_NUM_EMPLOYEES + 
                       EMPLOYER_YR_ESTAB,
                     data = perm, 
                     family = binomial())
# Display
tidy(full_log_cert)
```

#### Backwards selection

```{r backwards-select}
# Conduct backwards selection
selected_model <- step(full_log_cert, direction = "backward")

# Show variables
tidy(selected_model)
```

#### Cross validation

```{r lr-cross-validate}
# Partition into 10
train_control <- trainControl(method = "cv", number = 10)

# Sample 10%, crop for only selected variables
perm_crop <- perm %>% 
  drop_na(YEAR, JOB_INFO_EDUCATION,
          PW_AMOUNT_9089, EMPLOYER_NUM_EMPLOYEES,
          EMPLOYER_YR_ESTAB, CERT_BIN, PW_LEVEL_9089, COMPSCI) %>%
  select(YEAR, JOB_INFO_EDUCATION,
          PW_AMOUNT_9089, EMPLOYER_NUM_EMPLOYEES,
          EMPLOYER_YR_ESTAB, CERT_BIN, PW_LEVEL_9089, COMPSCI) %>%
  sample(0.10 * nrow(.))

# Cross validate
model <- train(factor(CERT_BIN) ~ YEAR + 
                       JOB_INFO_EDUCATION +
                       PW_AMOUNT_9089 +
                       EMPLOYER_NUM_EMPLOYEES + 
                       EMPLOYER_YR_ESTAB + COMPSCI,
              data = model_data,
              trControl = train_control,
              method = "glm", family = "binomial")

# Show results
print(model)
confusionMatrix(model)
summary(model)
```

### Modeling using caret

```{r perm_crop}
# perm_crop contains only the variables we will use
perm_crop <- perm %>%
  select(CERT_BIN, DECISION_DATE, JOB_INFO_EDUCATION, PW_AMOUNT_9089, EMPLOYER_NUM_EMPLOYEES, EMPLOYER_YR_ESTAB) %>%
  drop_na() %>%
  mutate(CERT_BIN = as.factor(case_when(
    CERT_BIN == 1 ~ "y",
    CERT_BIN == 0 ~ "n"
  ))) 
  #%>%
    #sample_n(1000)
perm_crop
```

```{r creating-control}
# create cross validation control
control <- trainControl(method="cv", number=10)
```
```{r svm}
# svm
cert_svm <- train(CERT_BIN ~ ., data = perm_crop, method="svmLinear", trControl = control, tuneLength=15)
cert_svm # print results
plot(predict(cert_svm, perm_crop)) # create prediction
confusionMatrix(cert_svm, dnn = c("Predicted", "Actual")) # display confusion matrix
```
```{r knn}
# k nearest neighbors
cert_knn <- train(CERT_BIN ~ ., data = perm_crop, method="knn", trControl = control)
cert_knn
plot(predict(cert_knn, perm_crop))
confusionMatrix(cert_knn, dnn = c("Predicted", "Actual"))
```
```{r rf}
# random forest
#cert_rf <- train(CERT_BIN ~ ., data = perm_crop, method="rf", trControl = control)
#cert_rf
#plot(predict(cert_rf, perm_crop))
#confusionMatrix(cert_rf, dnn = c("Predicted", "Actual"))
```
```{r glmm}
# generalized linear model (linear regression)
cert_glm <- train(CERT_BIN ~ ., data = perm_crop, method="glm", trControl = control)
cert_glm
plot(predict(cert_glm, perm_crop))
confusionMatrix(cert_glm, dnn = c("Predicted", "Actual"))
```